# Generated by Django 5.2.5 on 2025-09-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la sala', max_length=100)),
                ('code', models.CharField(help_text='Código único de identificación de la sala', max_length=10, unique=True)),
                ('capacity', models.IntegerField(help_text='Capacidad máxima de personas en la sala')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional de la sala')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sala está activa para uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de entrada a la sala')),
                ('exit_time', models.DateTimeField(blank=True, help_text='Fecha y hora de salida de la sala', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios sobre la entrada/salida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Sala a la que ingresa el monitor', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rooms.room')),
                ('user', models.ForeignKey(help_text='Monitor que ingresa a la sala', on_delete=django.db.models.deletion.CASCADE, related_name='room_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Entrada',
                'verbose_name_plural': 'Registros de Entrada',
                'ordering': ['-entry_time'],
            },
        ),
    ]
