# Generated by Django 4.2.25 on 2025-10-03 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomentry',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de entrada a la sala'),
        ),
    ]
