# Generated by Django 5.2 on 2025-10-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_fix_entry_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomentry',
            name='active',
            field=models.BooleanField(default=True, help_text='Indica si la entrada está activa'),
        ),
    ]
