[tool.ruff]
target-version = "py313"
line-length = 100
exclude = [
  "**/migrations/**",
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["F401", "F541", "F841"]
"test_*.py" = ["F401", "F541", "F841", "E402", "E722"]
"users/tests/*.py" = ["F401", "F541", "F841"]
"rooms/tests/*.py" = ["F401", "F541", "F841"]
"notifications/tests/*.py" = ["F401", "F541", "F841"]
"debug_*.py" = ["E402", "F401", "F541"]
"check_*.py" = ["E402", "F401"]
"verify_email_config.py" = ["E402", "F401"]
"fix_notification_table.py" = ["E402", "F401"]
"clean_active_entries.py" = ["E402", "F401"]

