# Generated by Django 5.2.5 on 2025-09-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Número de serie único del equipo', max_length=50, unique=True, verbose_name='Número de Serie')),
                ('name', models.CharField(help_text='Nombre o modelo del equipo', max_length=100, verbose_name='Nombre/Modelo')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del equipo', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('operational', 'Operativo'), ('maintenance', 'En mantenimiento'), ('out_of_service', 'Fuera de servicio')], default='operational', help_text='Estado actual del equipo', max_length=20, verbose_name='Estado')),
                ('acquisition_date', models.DateField(help_text='Fecha en que se adquirió el equipo', verbose_name='Fecha de Adquisición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Sala donde se encuentra el equipo', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='rooms.room', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['room', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(help_text='Descripción detallada del problema reportado', verbose_name='Descripción del Problema')),
                ('reported_date', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se reportó el problema', verbose_name='Fecha del Reporte')),
                ('resolved', models.BooleanField(default=False, help_text='Indica si el problema ha sido resuelto', verbose_name='Resuelto')),
                ('resolved_date', models.DateTimeField(blank=True, help_text='Fecha y hora en que se resolvió el problema', null=True, verbose_name='Fecha de Resolución')),
                ('resolution_notes', models.TextField(blank=True, help_text='Detalles sobre cómo se resolvió el problema', verbose_name='Notas de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipo que presenta el problema', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='equipment.equipment', verbose_name='Equipo')),
                ('reported_by', models.ForeignKey(help_text='Usuario que reporta el problema', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Reporte de Equipo',
                'verbose_name_plural': 'Reportes de Equipos',
                'ordering': ['-reported_date'],
            },
        ),
    ]
