# Generated by Django 5.2 on 2025-10-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentreport',
            name='issue_type',
            field=models.CharField(blank=True, help_text='Tipo de falla (texto libre, p. ej. hardware, software, red, etc.)', max_length=100, verbose_name='Tipo de Falla'),
        ),
    ]
