# Generated by Django 5.2.5 on 2025-09-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Fecha y hora de inicio del turno', verbose_name='Inicio del turno')),
                ('end_datetime', models.DateTimeField(help_text='Fecha y hora de finalización del turno', verbose_name='Fin del turno')),
                ('recurring', models.BooleanField(default=False, help_text='Indica si el turno se repite semanalmente', verbose_name='Recurrente')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el turno', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Administrador que creó el turno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('room', models.ForeignKey(help_text='Sala asignada para el turno', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rooms.room', verbose_name='Sala')),
                ('user', models.ForeignKey(help_text='Monitor asignado al turno', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Monitor')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['start_datetime'],
            },
        ),
    ]
