# Generated by Django 4.2.25 on 2025-10-06 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', help_text='Estado actual del turno', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(help_text='Administrador que creó el turno', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(help_text='Monitor asignado al turno', limit_choices_to={'is_verified': True, 'role': 'monitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Monitor'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='schedule_end_after_start'),
        ),
    ]
