# Generated by Django 4.2.25 on 2025-10-11 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_roomentry_active'),
        ('schedule', '0002_schedule_status_alter_schedule_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del curso', max_length=200, verbose_name='Nombre del Curso')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del curso', verbose_name='Descripción')),
                ('start_datetime', models.DateTimeField(help_text='Inicio del curso', verbose_name='Fecha y Hora de Inicio')),
                ('end_datetime', models.DateTimeField(help_text='Fin del curso', verbose_name='Fecha y Hora de Fin')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', help_text='Estado actual del curso', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Administrador que creó el curso', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('monitor', models.ForeignKey(help_text='Monitor responsable del curso', limit_choices_to={'is_verified': True, 'role': 'monitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to=settings.AUTH_USER_MODEL, verbose_name='Monitor a Cargo')),
                ('room', models.ForeignKey(help_text='Sala donde se impartirá el curso', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='rooms.room', verbose_name='Sala')),
                ('schedule', models.ForeignKey(help_text='Turno del monitor que debe cubrir este curso', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='schedule.schedule', verbose_name='Turno Asociado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creado'), ('update', 'Actualizado'), ('delete', 'Eliminado')], max_length=10, verbose_name='Acción')),
                ('changes', models.JSONField(default=dict, help_text='Detalles de los cambios realizados', verbose_name='Cambios')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Historial de Curso',
                'verbose_name_plural': 'Historiales de Cursos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='courses_cou_start_d_476cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['room', 'start_datetime'], name='courses_cou_room_id_a02fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['monitor', 'start_datetime'], name='courses_cou_monitor_07d6b6_idx'),
        ),
    ]
