# Generated by Django 4.2.25 on 2025-10-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_monitor_07d6b6_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='monitor',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['schedule', 'start_datetime'], name='courses_cou_schedul_b4ea35_idx'),
        ),
    ]
