# Generated by Django 5.2.5 on 2025-09-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del listado de asistencia', max_length=200, verbose_name='Título')),
                ('date', models.DateField(help_text='Fecha a la que corresponde el listado de asistencia', verbose_name='Fecha')),
                ('file', models.FileField(help_text='Archivo con el listado de asistencia (PDF recomendado)', upload_to='attendances/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional sobre el listado de asistencia', verbose_name='Descripción')),
                ('reviewed', models.BooleanField(default=False, help_text='Indica si el listado ha sido revisado por un administrador', verbose_name='Revisado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Administrador que revisó el listado de asistencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('uploaded_by', models.ForeignKey(help_text='Usuario que subió el listado de asistencia', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Listado de Asistencia',
                'verbose_name_plural': 'Listados de Asistencia',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Incapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio de la incapacidad', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Fecha de finalización de la incapacidad', verbose_name='Fecha de Finalización')),
                ('document', models.FileField(help_text='Documento que certifica la incapacidad (PDF recomendado)', upload_to='incapacities/', verbose_name='Documento de Incapacidad')),
                ('description', models.TextField(blank=True, help_text='Descripción o motivo de la incapacidad', verbose_name='Descripción')),
                ('approved', models.BooleanField(default=False, help_text='Indica si la incapacidad ha sido aprobada por un administrador', verbose_name='Aprobada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Administrador que aprobó la incapacidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_incapacities', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('user', models.ForeignKey(help_text='Monitor que presenta la incapacidad', on_delete=django.db.models.deletion.CASCADE, related_name='incapacities', to=settings.AUTH_USER_MODEL, verbose_name='Monitor')),
            ],
            options={
                'verbose_name': 'Incapacidad',
                'verbose_name_plural': 'Incapacidades',
                'ordering': ['-start_date'],
            },
        ),
    ]
