# Generated by Django 4.2.25 on 2025-10-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomentry_active'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Sala a la que corresponde el listado de asistencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Sala'),
        ),
    ]
