name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        DJANGO_ENV: testing
        SECRET_KEY: test-secret-key
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY || 'test_brevo_key' }}
        DEFAULT_FROM_EMAIL: "Test <test@example.com>"
        ALLOWED_HOSTS: "localhost,127.0.0.1"
        CORS_ALLOWED_ORIGINS: "http://localhost:3000"
        CSRF_TRUSTED_ORIGINS: "http://localhost:8000"
        PUBLIC_BASE_URL: "http://localhost:8000"
        FRONTEND_BASE_URL: "http://localhost:3000"
      run: |
        python manage.py test --verbosity=1