name: CI

on:
  push:
    branches: [ main, develop, produccion ]
  pull_request:
    branches: [ main, develop, produccion ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-v4-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-v4-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "=== Verifying critical packages ==="
          pip list | grep -i -E "whitenoise|dj-database-url|Django|djangorestframework"

      - name: Verify pytest installation
        run: |
          pip list | grep pytest
          python -c "import pytest; print(f'pytest version: {pytest.__version__}')"

      - name: Django checks
        env:
          SECRET_KEY: test-secret-key-for-ci-github-actions
          DEBUG: "False"
        run: |
          python manage.py check
          python manage.py makemigrations --check --dry-run

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: ds2_back.settings
          SECRET_KEY: test-secret-key-for-ci-github-actions
          DEBUG: "False"
        run: |
          python manage.py test --verbosity 1 --keepdb
